BookTea/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookTea.Context;
using BookTea.Models;
using System.Diagnostics.Metrics;

namespace BookTea.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHost;

        public BooksController(ApplicationDbContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            _webHost = webHost;
        }
        
        // GET: Books
        public async Task<IActionResult> Index(string term, string orderby, int CurrentPage=1)
        {
            var books = await _context.Books.Include(c => c.PublishingHouse).ToListAsync();
            //Search
            if (!String.IsNullOrEmpty(term))
            {
                books = books.Where(a => a.Description.Contains(term) || a.Price.ToString().Contains(term) ||
                                          a.Title.Contains(term) || a.Rating.ToString().Contains(term) ||
                                          a.Quantity.ToString().Contains(term) || a.ISBN.ToString().Contains(term) ||
                                          a.PublishingHouseId.ToString().Contains(term)).ToList();
            }

            // Sort
            ViewBag.OrderTitle = orderby == "Title" ? "Title_des" : "Title";
            ViewBag.OrderPrice = orderby == "Price" ? "Price_des" : "Price";
            ViewBag.OrderRating = orderby == "Rating" ? "Rating_des" : "Rating";
            ViewBag.OrderQuantity = orderby == "Quantity" ? "Quantity_des" : "Quantity";
            ViewBag.OrderPublishingHouse = orderby == "PublishingHouse" ? "PublishingHouse_des" : "PublishingHouse";

            switch (orderby)
            {
                case "Title":
                    books = books.OrderBy(b => b.Title).ToList();
                    break;
                case "Title_des":
                    books = books.OrderByDescending(b => b.Title).ToList();
                    break;
                case "Price":
                    books = books.OrderBy(b => b.Price).ToList();
                    break;
                case "Price_des":
                    books = books.OrderByDescending(b => b.Price).ToList();
                    break;
                case "Rating":
                    books = books.OrderBy(b => b.Rating).ToList();
                    break;
                case "Rating_des":
                    books = books.OrderByDescending(b => b.Rating).ToList();
                    break;
                case "Quantity":
                    books = books.OrderBy(b => b.Quantity).ToList();
                    break;
                case "Quantity_des":
                    books = books.OrderByDescending(b => b.Quantity).ToList();
                    break;
                case "PublishingHouse":
                    books = books.OrderBy(b => b.PublishingHouse.Name).ToList(); // Assuming PublishingHouse has a Name property
                    break;
                case "PublishingHouse_des":
                    books = books.OrderByDescending(b => b.PublishingHouse.Name).ToList();
                    break;
                default:
                    books = books.OrderBy(b => b.ISBN).ToList();
                    break;
            }

            //Pagination
            const int PageSize = 5;
            int TotalRecords = books.Count;
            int NumPages = (int)Math.Ceiling(Convert.ToDecimal(TotalRecords / (decimal)PageSize));
            ViewBag.NumPages = NumPages;
            ViewBag.CurrentPage = CurrentPage;
            ViewBag.TotalRecords = TotalRecords;
            books = books.Skip((CurrentPage - 1) * PageSize).Take(PageSize).ToList();

            return View(books);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.PublishingHouse)
                .FirstOrDefaultAsync(m => m.ISBN == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["PublishingHouse"] = new SelectList(_context.PublishingHouses, "Id", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ISBN,Title,Price,ImageFile,Rating,Description,Quantity,PublishingHouseId")] Book book)
        {
            if (ModelState.IsValid)
            {
                book.PhotoUrl = UploadImage(book);
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PublishingHouse"] = new SelectList(_context.PublishingHouses, "Id", "Name", book.PublishingHouseId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["PublishingHouseId"] = new SelectList(_context.PublishingHouses, "Id", "Name", book.PublishingHouseId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ISBN,Title,Price,ImageFile,Rating,Description,Quantity,PublishingHouseId")] Book book)
        {
            if (id != book.ISBN)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (book.ImageFile != null)
                    {
                        string uniqueFileName = UploadImage(book);
                        book.PhotoUrl = uniqueFileName;
                    }
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.ISBN))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PublishingHouseId"] = new SelectList(_context.PublishingHouses, "Id", "Name", book.PublishingHouseId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.PublishingHouse)
                .FirstOrDefaultAsync(m => m.ISBN == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Books == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Books'  is null.");
            }
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Books?.Any(e => e.ISBN == id)).GetValueOrDefault();
        }

        private string UploadImage(Book book)
        {
            string uniqueFileName = null;
            if (book.ImageFile != null)
            {
                string uploadsFolder = Path.Combine(_webHost.WebRootPath, "images"); //بيجيب فولدر الصور اللي هتنزل عليه
                uniqueFileName = Guid.NewGuid().ToString() + "_" + book.ImageFile.FileName; //اسم الملف الاصلي
                string filePath = Path.Combine(uploadsFolder, uniqueFileName); //لما بيدمج الاتنين بيكون دا مكان الصورة الجديد
                using (var fileStream = new FileStream(filePath, FileMode.Create)) //بينقل الصورة للمكان الجديد
                {
                    book.ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        private List<SelectListItem> GetPublishingHouse()
        {
            var LstPublishingHouse = new List<SelectListItem>();
            List<PublishingHouse> PublishingHouses = _context.PublishingHouses.ToList();
            LstPublishingHouse = PublishingHouses.Select(ph => new SelectListItem()
            {
                Value = ph.Id.ToString(),
                Text = ph.Name
            }).ToList();

BookTea/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookTea.Context;
using BookTea.Models;

namespace BookTea.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index(string term, string orderby = "Id", int CurrentPage = 1)
        {
            var customer = await _context.Customers.ToListAsync();

            //Search
            if (!String.IsNullOrEmpty(term))
            {
                customer = customer.Where(a => a.Name.Contains(term) ||
                a.Email.Contains(term) || a.DateOfBirth.ToString().Contains(term) || a.Address.Contains(term) ||
                a.Country.Contains(term)).ToList();

            }

            //Sort
            ViewBag.OrderName = orderby == "Name" ? "Name_des" : "Name";
            ViewBag.OrderEmail = orderby == "Email" ? "Email_des" : "Email";
            ViewBag.OrderDateOfBirth = orderby == "DateOfBirth" ? "DateOfBirth_des" : "DateOfBirth";
            ViewBag.OrderAddress = orderby == "Address" ? "Address_des" : "Address";
            ViewBag.OrderCountry = orderby == "Country" ? "Country_des" : "Country";
            switch (orderby)
            {
                case "Name":
                    customer = customer.OrderBy(a => a.Name).ToList();
                    break;
                case "Name_des":
                    customer = customer.OrderByDescending(a => a.Name).ToList();
                    break;
                case "Email":
                    customer = customer.OrderBy(a => a.Email).ToList();
                    break;
                case "Email_des":
                    customer = customer.OrderByDescending(a => a.Email).ToList();
                    break;
                case "DateOfBirth":
                    customer = customer.OrderBy(a => a.DateOfBirth).ToList();
                    break;
                case "DateOfBirth_des":
                    customer = customer.OrderByDescending(a => a.DateOfBirth).ToList();
                    break;
                case "Address":
                    customer = customer.OrderBy(a => a.Address).ToList();
                    break;
                case "Address_des":
                    customer = customer.OrderByDescending(a => a.Address).ToList();
                    break;
                case "Country":
                    customer = customer.OrderBy(a => a.Country).ToList();
                    break;
                case "Country_des":
                    customer = customer.OrderByDescending(a => a.Country).ToList();
                    break;
                default:
                    customer = customer.OrderBy(a => a.Id).ToList();
                    break;
            }

            //Pagination
            const int PageSize = 5;
            int TotalRecords = customer.Count;
            int NumPages = (int)Math.Ceiling(Convert.ToDecimal(TotalRecords / (decimal)PageSize));
            ViewBag.NumPages = NumPages;
            ViewBag.CurrentPage = CurrentPage;
            ViewBag.TotalRecords = TotalRecords;
            customer = customer.Skip((CurrentPage - 1) * PageSize).Take(PageSize).ToList();

            return View(customer);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Password,Name,Email,DateOfBirth,Address,Country")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Password,Name,Email,DateOfBirth,Address,Country")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Customers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Customers'  is null.");
            }
            var customer = await _context.Customers.FindAsync(id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
          return (_context.Customers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookTea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookTea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookTea.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookTea</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Customers
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="Customers" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="Customers" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Shipping Companies
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="ShippingCompanies" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="ShippingCompanies" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Books
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="Books" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="Books" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Publishing Houses
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="PublishingHouses" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="PublishingHouses" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <!--my order here : Rawan-->
                        <li class="nav-item dropdown">
                            <a class="nav-link" asp-controller="Orders" asp-action="Index">
                                Orders
                            </a>
                        </li>
                        <!--End my order here : Rawan-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Authors
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="Authors" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="Authors" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                BooksAuthors
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="BookAuthors" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="BookAuthors" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Cost Specification
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="CostSpecifications" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="CostSpecifications" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Payments
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-controller="Payments" asp-action="Index">Manage</a></li>
                                <li><a class="dropdown-item" asp-controller="Payments" asp-action="Create">Create</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookTea - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>